# Generated by Django 5.2.17 on 2026-09-21 10:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('clock_attendance', 'clock attendance'), ('request_leave', 'request leave'), ('request_overtime', 'request overtime'), ('view_own_payslip', 'view own payslip'), ('approve_requests', 'approve requests'), ('view_team_reports', 'view team reports'), ('manage_employees', 'manage employees'), ('export_employees', 'export employees'), ('run_payroll', 'run payroll'), ('view_all_payslips', 'view all payslips'), ('manage_settings', 'manage settings'), ('manage_sites', 'manage sites'), ('manage_schedules', 'manage schedules'), ('manage_payroll_rates', 'manage payroll rates'), ('manage_users', 'manage users'), ('view_audit_log', 'view audit log'), ('view_system_health', 'view system health'), ('view_checkpoint_module', 'view checkpoint module'), ('create_checkpoint_campaign', 'create checkpoint campaign'), ('activate_checkpoint_campaign', 'activate checkpoint campaign'), ('pause_checkpoint_campaign', 'pause checkpoint campaign'), ('end_checkpoint_campaign', 'end checkpoint campaign'), ('view_checkpoint_results', 'view checkpoint results'), ('review_checkpoint_exceptions', 'review checkpoint exceptions'), ('export_checkpoint_reports', 'export checkpoint reports'), ('manage_checkpoint_settings', 'manage checkpoint settings')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(max_length=60, unique=True)),
                ('profile_photo_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
                ('all_objects', accounts.models.AllUserManager()),
            ],
        ),
    ]
