# Generated by Django 5.2.17 on 2026-09-21 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=40)),
                ('verification_result', models.CharField(blank=True, max_length=60, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=60, null=True)),
                ('validation_message', models.CharField(blank=True, max_length=255, null=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('submission_attempts', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_result', models.CharField(blank=True, max_length=60, null=True)),
                ('issue_reported', models.CharField(blank=True, max_length=40, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('server_timestamp', models.DateTimeField(blank=True, null=True)),
                ('client_timestamp', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_accuracy_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distance_from_site_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('within_geofence', models.BooleanField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('network_status', models.CharField(blank=True, max_length=20, null=True)),
                ('employee_explanation', models.TextField(blank=True, null=True)),
                ('hr_reason', models.CharField(blank=True, max_length=40, null=True)),
                ('hr_note', models.TextField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='employees.employee')),
                ('matched_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.site')),
                ('project_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='employees.site')),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checkpoints',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('instruction', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, null=True)),
                ('response_window_minutes', models.PositiveIntegerField(default=10)),
                ('schedule_mode', models.CharField(blank=True, max_length=20, null=True)),
                ('scheduled_start_at', models.DateTimeField(blank=True, null=True)),
                ('random_window_start', models.TimeField(blank=True, null=True)),
                ('random_window_end', models.TimeField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, db_column='activated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, db_column='closed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paused_by', models.ForeignKey(blank=True, db_column='paused_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_campaigns', to='employees.site')),
            ],
            options={
                'db_table': 'checkpoint_campaigns',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('details', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='checkpoints.checkpoint')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='checkpoints.checkpointcampaign')),
            ],
            options={
                'db_table': 'checkpoint_audit_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='checkpoints.checkpointcampaign'),
        ),
        migrations.CreateModel(
            name='CheckpointReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('reason', models.CharField(blank=True, max_length=60, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='checkpoints.checkpoint')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checkpoint_reviews',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CheckpointCampaignParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='checkpoints.checkpointcampaign')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoint_participations', to='employees.employee')),
            ],
            options={
                'db_table': 'checkpoint_campaign_participants',
                'unique_together': {('campaign', 'employee')},
            },
        ),
    ]
