# Generated by Django 5.2.17 on 2026-09-21 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(max_length=20)),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('employee_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('employer_rate', models.DecimalField(decimal_places=4, max_digits=8)),
                ('ec_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effective_year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'contribution_rates',
                'ordering': ['contribution_type', 'min_salary'],
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('group_id', models.CharField(blank=True, max_length=36, null=True)),
                ('description', models.CharField(max_length=255)),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('starts_on', models.DateField()),
                ('status', models.CharField(default='active', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, db_column='cancelled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_deductions', to='employees.employee')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.site')),
            ],
            options={
                'db_table': 'payroll_deductions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('cutoff_type', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='open', max_length=20)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('reminded_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, db_column='closed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, db_column='released_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_periods',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PayrollItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('night_diff_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('holiday_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('late_undertime_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('absences_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('half_day_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sss_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('philhealth_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pagibig_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('withholding_tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('missing_item_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('adjusted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('adjusted_by', models.ForeignKey(blank=True, db_column='adjusted_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_items', to='employees.employee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'payroll_items',
                'unique_together': {('employee', 'payroll_period')},
            },
        ),
        migrations.CreateModel(
            name='PayrollDeductionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deduction', models.ForeignKey(db_column='payroll_deduction_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payroll.payrolldeduction')),
                ('payroll_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_payments', to='payroll.payrollitem')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'payroll_deduction_payments',
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('payroll_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payslip', to='payroll.payrollitem')),
            ],
            options={
                'db_table': 'payslips',
            },
        ),
    ]
