# Generated by Django 5.2.17 on 2026-09-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='admin_remarks',
        ),
    ]
