# Generated by Django 5.2.17 on 2026-09-21 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=10)),
                ('logged_at', models.DateTimeField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('distance_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gps_accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('within_geofence', models.BooleanField(default=False)),
                ('location_status', models.CharField(blank=True, max_length=40, null=True)),
                ('location_validation_message', models.CharField(blank=True, max_length=255, null=True)),
                ('location_reason', models.TextField(blank=True, null=True)),
                ('location_verification_status', models.CharField(blank=True, max_length=20, null=True)),
                ('location_remarks', models.TextField(blank=True, null=True)),
                ('location_verified_at', models.DateTimeField(blank=True, null=True)),
                ('photo_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('synced_offline', models.BooleanField(default=False)),
                ('ot_verification_status', models.CharField(blank=True, max_length=20, null=True)),
                ('ot_remarks', models.TextField(blank=True, null=True)),
                ('ot_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('assigned_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='employees.site')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='employees.employee')),
                ('location_verified_by', models.ForeignKey(blank=True, db_column='location_verified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ot_verified_by', models.ForeignKey(blank=True, db_column='ot_verified_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='employees.site')),
            ],
            options={
                'db_table': 'attendance_logs',
                'ordering': ['logged_at'],
            },
        ),
    ]
